services:
  s3_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: s3_api
    container_name: s3_api
    command: python -m app.s3_api.src
#    command: ["sh", "-c", "sleep infinity"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    env_file:
      - .env
    hostname: ${RABBITMQ_HOST}
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

    ports:
      - "15672:15672"
      - "5672:5672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: bot
    container_name: sender_bot
    env_file: .env
    command: python -m app.bot.src
#    command: ["sh", "-c", "sleep infinity"]
    restart: unless-stopped
    depends_on:
      - s3_api

  postgres:
    container_name: db_postgres
    image: postgres:18-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "${DB_PORT}:5432"

  redis:
    container_name: redis
    image: redis:7.4-alpine
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redisdata:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pgdata:
  redisdata:
  rabbitmq_data: