services:
  bot:
    image: lalka618/sender-bot:latest
    container_name: tg_bot
    env_file: .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    container_name: db_postgres
    image: postgres:18-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d practice -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "${DB_PORT}:5432"

  redis:
    container_name: redis
    image: redis:7.4-alpine
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redisdata:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pgdata:
  redisdata: