"""Add Receiver table

Revision ID: 3fdca8d7b0ec
Revises: df68c2380436
Create Date: 2026-01-24 15:56:38.003543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdca8d7b0ec'
down_revision: Union[str, Sequence[str], None] = 'df68c2380436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receivers',
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receivers')
    # ### end Alembic commands ###
