"""Add enum status field to 'mailings' table

Revision ID: 5cd0bd81341b
Revises: 0c0abc13793e
Create Date: 2026-03-25 18:32:39.400939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd0bd81341b'
down_revision: Union[str, Sequence[str], None] = '0c0abc13793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('s3_key', sa.VARCHAR(length=255), nullable=True))
    op.add_column('mailings', sa.Column('save_status', sa.Enum('0', '1', '2', name='mailingstatus', native_enum=False), server_default='1', nullable=False))
    op.drop_column('mailings', 'csv_result_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('csv_result_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('mailings', 'save_status')
    op.drop_column('mailings', 's3_key')
    # ### end Alembic commands ###
