"""initial migration

Revision ID: 78bdeda81e37
Revises: 18ba9f2c4a36
Create Date: 2026-01-26 21:05:16.009091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bdeda81e37'
down_revision: Union[str, Sequence[str], None] = '18ba9f2c4a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('formated_description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'formated_description')
    # ### end Alembic commands ###
