"""Template table: change type of created_at column from DateTiem to TimeStamp

Revision ID: 474c39b35053
Revises: d6978cbf3b44
Create Date: 2026-01-27 16:45:59.411987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474c39b35053'
down_revision: Union[str, Sequence[str], None] = 'd6978cbf3b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
