"""Template table: add creator_id

Revision ID: c48336767829
Revises: 474c39b35053
Create Date: 2026-01-30 15:07:03.982335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48336767829'
down_revision: Union[str, Sequence[str], None] = '474c39b35053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'templates', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'creator_id')
    # ### end Alembic commands ###
