"""Initial migration

Revision ID: d6978cbf3b44
Revises: 78bdeda81e37
Create Date: 2026-01-27 16:41:49.283108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6978cbf3b44'
down_revision: Union[str, Sequence[str], None] = '78bdeda81e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'created_at')
    # ### end Alembic commands ###
